### ISSUE TITLE
SQL Error when trying to access web app

### ISSUE THREAD

**Issue by Mayopi** [GusniarNanda/SDNBulupayung03#1]
### Problem View
Error SQL ketika mencoba akses halaman website path `/`
Stacktrace:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sdn-bulupayung-03.visimisi' doesn't exist (SQL: select * from `visimisi` limit 1)`

### Evidence
![image](https://github.com/user-attachments/assets/7e9233eb-d121-4b3c-96a4-bd2e5682ce33)

### Expectation
Dapat mengakses halaman website tanpa error

### Solution
Table yang berhubungan dengan model VisiMisi tidak di temukan

```php
    public function index()
    {
        $sliders = Slider::all();
        $services = Service::all();
        $portofolios = Portofolio::all();
        $visimisi = VisiMisi::first();
        return view('home.index', compact('sliders' , 'services', 'portofolios', 'visimisi'));
    }
```

![image](https://github.com/user-attachments/assets/1dd4b0bb-0175-4e79-9bba-b4a6ec26e61a)

### Step to reproduce
- clone repository
- npm install & composer install
- setup .env file & database
- run command `php artisan migrate:fresh`
- runc command `npm run dev & php artisan serve`
- navigate to `http://localhost:8000`

**Comment by GusniarNanda** [comment]
Fix
