### ISSUE TITLE
Attempting to read undefined value of VisiMisi

### ISSUE THREAD

**Issue by Mayopi** [GusniarNanda/SDNBulupayung03#3]
### Problem Overview
saat menginisialisasi project dengan command `php artisan migrate:fresh --seed` dan `php artisan serve` terjadi error attempted to read property visi misi on null

### Evidence
![image](https://github.com/user-attachments/assets/f38a8740-d82b-4ff1-b7ac-c9c3166b2100)

### Solution
Tambahkan visi misi seeder pada main seeder

**Comment by GusniarNanda** [comment]
Fix
